### ISSUE TITLE
Tree Fellter not giving saplings

### ISSUE THREAD

**Issue by Zaphara94** [Zaphara94/SFMC-Minecraft-Network#1]
Vanilla Server
When using Tree Feller ability with mcmmo, no saplings are dropping.

**Comment by Ironfire4766** [comment]
I have been receiving this exact issue on my own server and was hoping to find a solution. Whenever I use treefeller none of the leaves broken by treefeller itself drop any saplings, sticks, or apples.

we are playing on 1.16.4 spigot.

**Comment by Zaphara94** [comment]
We resolved this issue by making sure we had the latest mcmmo version installed on ohr server. It seems there are a few versions in which treefeller is broken in this way. 

https://papermc.io/ci/view/%20%20Plugins/job/mcMMO/
